# Deployment workflow

# Event/Workflow name
name: Deployment Project

# Event Triggers ->Controls when the workflow will run (events that trigger the workflow)
# push -> Allows you to run this workflow every time you push to the repository
# workflow_dispatch -> Allows you to run this workflow manually from the Actions tab
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Stablish the workflow jobs by identation:
  
  # First job defined for this workflow -> lint
  lint-job:

    # The type of runner that the job will run on -> Github actions runners (OSs available)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Let the github remote server get the repository code before anything else to be able to run the tests
      - name: Get the code
        # Search for actions in the github marketplace -> checkout action (or github actions checkout)
        # (Checkout action): Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it -> download the repository code
        uses: actions/checkout@v6.0.2
        # To change any settings of the checkout action, you can use the "with" keyword to specify the parameters of the action
        #with: ...

      # No needed, it's preinstalled in the runner selected,
      # but if you want to specify the version of node.js you want to use or it wouldn't be preinstalled -> you can use the "setup-node" action
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Install dependencies using 'npm ci' (continuous integration) -> install the exact version of the project dependencies (npm install could install breaking version dependencies) 
      - name: Install dependencies
        run: npm ci

      # Run lint using 'npm run lint' -> run the lint script defined in the package.json file
      - name: Run lint
        run: npm run lint

  # Second job defined for this workflow -> tests
  test-job:

    # This job will only run if the lint-job has completed successfully
    needs: lint-job

    # Initial same steps than before
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6.0.2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci

      # Run tests using 'npm test' -> run the test script defined in the package.json file
      - name: Run tests
        run: npm test

  # Third job defined for this workflow to deploy to a hosting server -> deploy
  deploy-job:

    # This job will only run if the lint-job and test-job have completed successfully -> can be an array of jobs [job1, job2, ...]
    needs: [lint-job, test-job]
    
    # Initial same steps than before
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6.0.2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci

      # Build the project using 'npm run build' -> run the build script defined in the package.json file to create the production build of the project
      - name: Build project
        run: npm run build

      # Deploy to hosting server -> here you would add the actual deployment commands, such as using scp, rsync, or a deployment action from the marketplace
      - name: Deploy
        run: echo "Deploying to hosting server..." # Simulate deployment command, replace with actual deployment commands
    
